[package]
name = "ratum"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
build = "../build.rs"

[features]
test-support = []

[dependencies]
base64.workspace = true
blake2.workspace = true
bytes.workspace = true
dryoc.workspace = true
hex.workspace = true
log.workspace = true
minreq.workspace = true
mio.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tiny_http.workspace = true

[dev-dependencies]
ratum = { path = ".", features = ["test-support"] }
